const contactsData = [
  {
    "id": "nat_999",
    "service_name_en": "National Emergency Service",
    "service_name_bn": "জাতীয় জরুরি সেবা",
    "contact_name": "National Emergency Desk",
    "phone_number": "999",
    "phone_type": "Shortcode",
    "category": "Emergency",
    "description_en": "Primary national emergency hotline for police, fire, and ambulance dispatch.",
    "description_bn": "পুলিশ, ফায়ার সার্ভিস ও অ্যাম্বুলেন্স সেবার জন্য জাতীয় জরুরি নম্বর।",
    "availability": "24/7",
    "toll_free": "True",
    "coverage": "Nationwide",
    "organization_en": "Bangladesh Police / Ministry of Home Affairs",
    "organization_bn": "বাংলাদেশ পুলিশ / স্বরাষ্ট্র মন্ত্রণালয়",
    "source_name": "Bangladesh National Portal",
    "source_url": "https://bangladesh.gov.bd/pages/static-pages/69a55ba386514399668e4e89",
    "last_verified": "2026-08-04",
    "status": "Verified",
    "contact_notes": "Direct emergency dispatch",
    "notes": "Toll-free core national helpline across all operators."
  },
  {
    "id": "info_333",
    "service_name_en": "National Call Center & Citizen Support",
    "service_name_bn": "জাতীয় তথ্য ও সেবা কেন্দ্র",
    "contact_name": "National Call Center",
    "phone_number": "333",
    "phone_type": "Shortcode",
    "category": "Government",
    "description_en": "Information on government services, social relief, and reporting public grievances.",
    "description_bn": "সরকারি সেবা, তথ্য, সামাজিক সহায়তা ও অভিযোগ জানানোর জন্য জাতীয় কল সেন্টার।",
    "availability": "24/7",
    "toll_free": "Unknown",
    "coverage": "Nationwide",
    "organization_en": "Aspire to Innovate (a2i) / ICT Division",
    "organization_bn": "এটুআই / তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
    "source_name": "a2i Portal / National Portal",
    "source_url": "https://333.gov.bd/",
    "last_verified": "2026-08-04",
    "status": "Verified",
    "contact_notes": "National information helpdesk",
    "notes": "Operator airtime charges vary; officially declared free for specific relief queries."
  },
  {
    "id": "helpline_109",
    "service_name_en": "Violence Against Women & Children Helpline",
    "service_name_bn": "নারী ও শিশু নির্যাতন প্রতিরোধ সেল",
    "contact_name": "Helpline Desk",
    "phone_number": "109",
    "phone_type": "Shortcode",
    "category": "Women & Children",
    "description_en": "Emergency protection, counseling, and legal support for women and children facing violence.",
    "description_bn": "নারী ও শিশু নির্যাতন প্রতিরোধে জরুরি আইনি সহায়তা, কাউন্সেলিং ও সুরক্ষা।",
    "availability": "24/7",
    "toll_free": "True",
    "coverage": "Nationwide",
    "organization_en": "Ministry of Women and Children Affairs (MoWCA)",
    "organization_bn": "মহিলা ও শিশু বিষয়ক মন্ত্রণালয়",
    "source_name": "Ministry of Women & Children Affairs",
    "source_url": "https://bangladesh.gov.bd/pages/static-pages/69a55ba386514399668e4e89",
    "last_verified": "2026-08-04",
    "status": "Verified",
    "contact_notes": "Emergency protection desk",
    "notes": "Replaced legacy 10921 shortcode."
  },
  {
    "id": "child_1098",
    "service_name_en": "Child Helpline",
    "service_name_bn": "শিশু সহায়তামূলক নম্বর",
    "contact_name": "Child Protection Desk",
    "phone_number": "1098",
    "phone_type": "Shortcode",
    "category": "Women & Children",
    "description_en": "Dedicated helpline for emergency protection and rescue of children in distress.",
    "description_bn": "ঝুঁকিতে থাকা বা বিপদে পড়া শিশুদের জরুরি সুরক্ষা ও সহায়তা সেবা।",
    "availability": "24/7",
    "toll_free": "True",
    "coverage": "Nationwide",
    "organization_en": "Department of Social Services / UNICEF",
    "organization_bn": "সমাজসেবা অধিদপ্তর",
    "source_name": "Department of Social Services",
    "source_url": "https://bangladesh.gov.bd/pages/static-pages/69a55ba386514399668e4e89",
    "last_verified": "2026-08-04",
    "status": "Verified",
    "contact_notes": "Child rescue hotline",
    "notes": "Officially recognized toll-free child protection helpline."
  },
  {
    "id": "disaster_1090",
    "service_name_en": "Disaster Early Warning Support",
    "service_name_bn": "দুর্যোগের আগাম বার্তা",
    "contact_name": "Disaster Warning IVR",
    "phone_number": "1090",
    "phone_type": "Shortcode",
    "category": "Emergency",
    "description_en": "Interactive voice response for weather alerts, cyclone warnings, and flood updates.",
    "description_bn": "ঘূর্ণিঝড়, বন্যা ও দুর্যোগের আবহাওয়া সংক্রান্ত আগাম বার্তা।",
    "availability": "24/7",
    "toll_free": "True",
    "coverage": "Nationwide",
    "organization_en": "Ministry of Disaster Management and Relief",
    "organization_bn": "দুর্যোগ ব্যবস্থাপনা ও ত্রাণ মন্ত্রণালয়",
    "source_name": "Ministry of Disaster Management & Relief",
    "source_url": "https://bangladesh.gov.bd/pages/static-pages/69a55ba386514399668e4e89",
    "last_verified": "2026-08-04",
    "status": "Verified",
    "contact_notes": "Automated IVR system",
    "notes": "Toll-free automated weather alert service."
  },
  {
    "id": "land_16122",
    "service_name_en": "Land Service Citizen Hotline",
    "service_name_bn": "ভূমি সেবা সিটিজেন হটলাইন",
    "contact_name": "Land Service Call Center",
    "phone_number": "16122",
    "phone_type": "Shortcode",
    "category": "Government",
    "description_en": "Information and support for online land mutation (e-namjari) and land development tax.",
    "description_bn": "ই-নামজারি, ভূমি উন্নয়ন কর ও ভূমি সংক্রান্ত যাবতীয় সেবার তথ্য ও সহায়তা।",
    "availability": "24/7",
    "toll_free": "Unknown",
    "coverage": "Nationwide",
    "organization_en": "Ministry of Land",
    "organization_bn": "ভূমি মন্ত্রণালয়",
    "source_name": "Ministry of Land Portal",
    "source_url": "https://hotline.land.gov.bd/",
    "last_verified": "2026-08-04",
    "status": "Verified",
    "contact_notes": "Citizen land support desk",
    "notes": "Direct helpline for land tax and digital e-namjari services."
  },
  {
    "id": "legal_16430",
    "service_name_en": "National Legal Aid Helpline",
    "service_name_bn": "জাতীয় আইনগত সহায়তা সেবা",
    "contact_name": "Legal Aid Support Desk",
    "phone_number": "16430",
    "phone_type": "Shortcode",
    "category": "Government",
    "description_en": "Government-provided free legal aid, advice, and counseling for underprivileged citizens.",
    "description_bn": "অসচ্ছল ও সুবিধাবঞ্চিত নাগরিকদের সরকারি খরচে বিনামূল্যে আইনি পরামর্শ।",
    "availability": "24/7",
    "toll_free": "True",
    "coverage": "Nationwide",
    "organization_en": "National Legal Aid Services Organization (NLASO)",
    "organization_bn": "জাতীয় আইনগত সহায়তা প্রদান সংস্থা",
    "source_name": "NLASO Portal",
    "source_url": "https://buripotaup.meherpur.gov.bd/pages/video-galleries/national-helpline-for-government-legal-aid-services-16430-inauguration-conversation-2ffcc2-6980ddd635ce18e1c06f831e",
    "last_verified": "2026-08-04",
    "status": "Verified",
    "contact_notes": "Free legal advice desk",
    "notes": "Officially inaugurated free government legal assistance line."
  },
  {
    "id": "health_16263",
    "service_name_en": "Shasthya Batayan (Health Line)",
    "service_name_bn": "স্বাস্থ্য বাতায়ন",
    "contact_name": "Doctor Teleconsultation Desk",
    "phone_number": "16263",
    "phone_type": "Shortcode",
    "category": "Healthcare",
    "description_en": "Teleconsultation with registered doctors, hospital information, and ambulance contacts.",
    "description_bn": "২৪/৭ রেজিস্টার্ড ডাক্তারের চিকিৎসা পরামর্শ ও স্বাস্থ্য সংক্রান্ত তথ্য সেবা।",
    "availability": "24/7",
    "toll_free": "False",
    "coverage": "Nationwide",
    "organization_en": "Directorate General of Health Services (DGHS)",
    "organization_bn": "স্বাস্থ্য অধিদপ্তর",
    "source_name": "DGHS Portal",
    "source_url": "https://16263.dghs.gov.bd/",
    "last_verified": "2026-08-04",
    "status": "Verified",
    "contact_notes": "Doctor teleconsultation call center",
    "notes": "Standard airtime charges apply. Explicitly labeled non-toll-free by DGHS."
  },
  {
    "id": "acc_106",
    "service_name_en": "Anti-Corruption Commission Hotline",
    "service_name_bn": "দুদক হটলাইন",
    "contact_name": "Corruption Complaint Desk",
    "phone_number": "106",
    "phone_type": "Shortcode",
    "category": "Government",
    "description_en": "Helpline to lodge complaints regarding corruption, bribery, and illegal financial activities.",
    "description_bn": "দুর্নীতি, ঘুষ গ্রহণ ও সরকারি অনিয়ম সংক্রান্ত অভিযোগ জানানোর নম্বর।",
    "availability": "Business Hours",
    "toll_free": "True",
    "coverage": "Nationwide",
    "organization_en": "Anti-Corruption Commission (ACC)",
    "organization_bn": "দুর্নীতি দমন কমিশন",
    "source_name": "Anti-Corruption Commission",
    "source_url": "https://dgfood.gov.bd/pages/static-pages/6922dbca933eb65569e0c8e2",
    "last_verified": "2026-08-04",
    "status": "Verified",
    "contact_notes": "Complaint reception desk",
    "notes": "Live agents respond during working hours. Toll-free line."
  },
  {
    "id": "rab_101",
    "service_name_en": "RAB Control Room",
    "service_name_bn": "র‌্যাব কন্ট্রোল রুম",
    "contact_name": "Central Control Room Operator",
    "phone_number": "101",
    "phone_type": "Shortcode",
    "category": "Law & Order",
    "description_en": "Direct hotline for Rapid Action Battalion to report severe crimes and security threats.",
    "description_bn": "অপরাধ দমন ও নিরাপত্তা সংক্রান্ত তথ্য দেওয়ার জন্য র‌্যাবের সরাসরি হটলাইন।",
    "availability": "24/7",
    "toll_free": "Unknown",
    "coverage": "Nationwide",
    "organization_en": "Rapid Action Battalion",
    "organization_bn": "র‍্যাপিড অ্যাকশন ব্যাটালিয়ন",
    "source_name": "Rapid Action Battalion / National Portal",
    "source_url": "https://padmakarup.jhenaidah.gov.bd/pages/static-pages/69812e0235ce18e1c06fa3bd",
    "last_verified": "2026-08-04",
    "status": "Verified",
    "contact_notes": "RAB central helpdesk",
    "notes": "Direct national security hotline."
  },
  {
    "id": "fire_16163",
    "service_name_en": "Fire Service Central Control Room",
    "service_name_bn": "ফায়ার সার্ভিস কন্ট্রোল রুম",
    "contact_name": "Emergency Dispatcher",
    "phone_number": "16163",
    "phone_type": "Shortcode",
    "category": "Emergency",
    "description_en": "Direct hotline for fire emergency dispatch, rescue operations, and drowning response.",
    "description_bn": "অগ্নিকাণ্ড ও জরুরি উদ্ধার কাজের জন্য ফায়ার সার্ভিস কন্ট্রোল রুম হটলাইন।",
    "availability": "24/7",
    "toll_free": "Unknown",
    "coverage": "Nationwide",
    "organization_en": "Fire Service & Civil Defence (FSCD)",
    "organization_bn": "ফায়ার সার্ভিস ও সিভিল ডিফেন্স",
    "source_name": "Fire Service / CMCH Portal",
    "source_url": "https://cmch.gov.bd/hotlines",
    "last_verified": "2026-08-04",
    "status": "Verified",
    "contact_notes": "Dispatch control center",
    "notes": "Central mobile shortcode for fire and rescue emergencies."
  },
  {
    "id": "election_105",
    "service_name_en": "NID & Election Commission Hotline",
    "service_name_bn": "এনআইডি ও নির্বাচন কমিশন হেল্পলাইন",
    "contact_name": "NID Service Call Center",
    "phone_number": "105",
    "phone_type": "Shortcode",
    "category": "Government",
    "description_en": "Inquiries regarding National ID card corrections, status tracking, and voter info.",
    "description_bn": "জাতীয় পরিচয়পত্র (NID) সংশোধন, স্ট্যাটাস চেক ও ভোটার সংক্রান্ত তথ্যের জন্য।",
    "availability": "Business Hours",
    "toll_free": "Unknown",
    "coverage": "Nationwide",
    "organization_en": "Election Commission Secretariat",
    "organization_bn": "নির্বাচন কমিশন সচিবালয়",
    "source_name": "Election Commission NID Wing",
    "source_url": "https://www.nidw.gov.bd/nidwContact.php",
    "last_verified": "2026-08-04",
    "status": "Verified",
    "contact_notes": "NID helpdesk",
    "notes": "Call center operates during official government office hours."
  },
  {
    "id": "passport_16445",
    "service_name_en": "Passport & Immigration Call Center",
    "service_name_bn": "পাসপোর্ট ও ইমিগ্রেশন কল সেন্টার",
    "contact_name": "Passport Information Operator",
    "phone_number": "16445",
    "phone_type": "Shortcode",
    "category": "Government",
    "description_en": "Inquiries regarding e-passport application status, errors, and travel guidance.",
    "description_bn": "ই-পাসপোর্ট আবেদন, স্ট্যাটাস চেক ও ইমিগ্রেশন সংক্রান্ত তথ্যের জন্য কল সেন্টার।",
    "availability": "24/7",
    "toll_free": "Unknown",
    "coverage": "Nationwide",
    "organization_en": "Department of Immigration and Passports (DIP)",
    "organization_bn": "বহিরাগমন ও পাসপোর্ট অধিদপ্তর",
    "source_name": "Department of Immigration and Passports",
    "source_url": "https://dipeast.dhaka.gov.bd/",
    "last_verified": "2026-08-04",
    "status": "Verified",
    "contact_notes": "Passport call center",
    "notes": "Official e-passport and immigration support hotline."
  },
  {
    "id": "consumer_16121",
    "service_name_en": "National Consumer Rights Helpline",
    "service_name_bn": "জাতীয় ভোক্তা অধিকার সংরক্ষণ হেল্পলাইন",
    "contact_name": "National Consumer Complaint Center",
    "phone_number": "16121",
    "phone_type": "Shortcode",
    "category": "Government",
    "description_en": "Helpline for lodging complaints regarding consumer fraud, price manipulation, and sub-standard products.",
    "description_bn": "দ্রব্যমূল্য বৃদ্ধি, ভেজাল পণ্য ও ভোক্তা অধিকার লঙ্ঘনের অভিযোগ জানানোর হেল্পলাইন।",
    "availability": "24/7",
    "toll_free": "Unknown",
    "coverage": "Nationwide",
    "organization_en": "Directorate of National Consumer Rights Protection",
    "organization_bn": "জাতীয় ভোক্তা-অধিকার সংরক্ষণ অধিদপ্তর",
    "source_name": "Directorate of National Consumer Rights Protection (DNCRP)",
    "source_url": "https://dncrp.gov.bd/",
    "last_verified": "2026-08-04",
    "status": "Verified",
    "contact_notes": "Consumer complaint desk",
    "notes": "Verified replacement for invalid 14521. Officially active hotline on dncrp.gov.bd."
  }
];
